# Generated by Django 3.0.6 on 2020-05-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200523_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Middle Name'),
        ),
    ]
