# Generated by Django 3.0.6 on 2020-05-23 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_university_year'),
        ('users', '0003_auto_20200523_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='university',
        ),
        migrations.RemoveField(
            model_name='user',
            name='university',
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='klass',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], null=True, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='symbol',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Class Symbol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='klass',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], null=True, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='user',
            name='symbol',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Class Symbol'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_year', models.CharField(max_length=128, verbose_name='Admission Year')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.University', verbose_name='University')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
