# Generated by Django 3.0.6 on 2020-05-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200523_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='parents',
            field=models.ManyToManyField(to='users.Parent'),
        ),
    ]
