# Generated by Django 3.0.6 on 2020-05-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200523_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='middle_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='job',
            field=models.CharField(max_length=128, verbose_name='Job'),
        ),
    ]
