# Generated by Django 3.0.6 on 2020-05-23 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internals', '0002_school_university'),
        ('users', '0009_auto_20200523_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='school',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='internals.School', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internals.University', verbose_name='University'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internals.School', verbose_name='School'),
        ),
    ]
