# Generated by Django 3.0.6 on 2020-05-23 23:23

from django.db import migrations, models
import internals.models


class Migration(migrations.Migration):

    dependencies = [
        ('internals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='Full Name of School')),
                ('headmaster', models.CharField(blank=True, default='', max_length=128, verbose_name="Headmaster's Full Name")),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='Full name of University')),
                ('location', models.CharField(max_length=128, verbose_name='Location')),
                ('logo', models.ImageField(upload_to=internals.models.University.get_logo_upload_path, verbose_name='University Logo')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
    ]
