# Generated by Django 3.0.6 on 2020-05-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='Full Name of School')),
                ('head', models.CharField(max_length=128, verbose_name="Headmaster's Full Name")),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='Full name of University')),
                ('location', models.CharField(max_length=128, verbose_name='Location')),
                ('year', models.CharField(max_length=128, verbose_name='Admission Year')),
                ('logo', models.ImageField(upload_to='', verbose_name='University Logo')),
            ],
        ),
    ]
