# Generated by Django 3.0.6 on 2020-05-23 17:06

import internals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='head',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name="Headmaster's Full Name"),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(upload_to=internals.models.University.get_logo_upload_path, verbose_name='University Logo'),
        ),
    ]
