# Generated by Django 3.0.6 on 2020-05-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200523_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='head',
            new_name='headmaster',
        ),
    ]
