# Generated by Django 3.0.6 on 2020-05-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200523_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='year',
        ),
    ]
