# Generated by Django 3.0.6 on 2020-05-23 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200524_0223'),
        ('core', '0004_remove_university_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
