# Generated by Django 3.0.6 on 2020-05-23 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200524_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='halloffamemember',
            options={'ordering': ('order',), 'verbose_name': 'Hall of Fame Member', 'verbose_name_plural': 'Hall of Fame Members'},
        ),
        migrations.AlterModelOptions(
            name='historicalhalloffamemember',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Hall of Fame Member'},
        ),
    ]
