# Generated by Django 3.0.6 on 2020-05-24 00:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0002_historicaltopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='source',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='url',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='task',
            name='authors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
